name: doctor_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl:
  flutter_spinkit:
  flutter:
    sdk: flutter
  flutter_core:
    git:
      url: https://gitlab.com/widebitsbd/flutter_core
      ref: master
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - langs/
    - assets/images/
    - assets/icons/
